import { AlertTriangle, ArrowUpRight, BookOpenCheck, CheckCircle2 } from 'lucide-react';
import Link from 'next/link';
import { Footer } from '@/components/layout/Footer';
import { DirectAnswerBlock } from '@/components/ui/DirectAnswerBlock';
import { FAQSchema } from '@/components/ui/FAQSchema';
import { RelatedTools } from '@/components/ui/RelatedTools';
import PercentageCalculatorClient from './PercentageCalculatorClient';
import { PERCENTAGE_TOOL_CONFIGS, type PercentageToolKind } from './percentage-tool-data';

export default function PercentageToolPage({ kind }: { kind: PercentageToolKind }) {
  const config = PERCENTAGE_TOOL_CONFIGS[kind];
  return <div className="min-h-screen bg-[var(--bg-primary)]">
    <header className="relative overflow-hidden px-4 pb-10 pt-14 text-center sm:pb-14 sm:pt-20"><div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(to_right,rgba(15,23,42,0.045)_1px,transparent_1px),linear-gradient(to_bottom,rgba(15,23,42,0.045)_1px,transparent_1px)] bg-[size:38px_38px] [mask-image:linear-gradient(to_bottom,black,transparent)]" /><div className="relative mx-auto max-w-4xl"><p className="mb-4 text-xs font-black uppercase tracking-[0.2em] text-blue-700">{config.eyebrow}</p><h1 className="text-[clamp(2.2rem,7vw,4.5rem)] font-black leading-[0.98] tracking-[-0.045em] text-slate-950">{config.title}</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">{config.subtitle}</p></div></header>
    <PercentageCalculatorClient kind={kind} />
    <main className="percentage-tool-content mx-auto max-w-6xl px-4 sm:px-6">
      <DirectAnswerBlock title={config.explanationTitle} answer={config.directAnswer} keyTakeaways={config.steps} categoryName="Percentage calculators" />
      <section className="grid gap-6 py-10 lg:grid-cols-[1.15fr_0.85fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><BookOpenCheck size={20} /></span><h2 className="text-2xl font-black tracking-tight text-slate-950">{config.explanationTitle}</h2></div><p className="leading-7 text-slate-600">{config.explanation}</p><div className="mt-6 rounded-xl bg-slate-950 p-5 text-white"><p className="text-[0.68rem] font-black uppercase tracking-[0.18em] text-cyan-300">Formula</p><code className="mt-2 block whitespace-pre-wrap text-sm leading-6 text-slate-100">{config.formula}</code></div></div><div className="rounded-2xl border border-blue-200 bg-blue-50/60 p-6 sm:p-8"><h2 className="text-xl font-black text-slate-950">How to use this {config.title.toLowerCase()}</h2><ol className="mt-6 space-y-5">{config.steps.map((step, index) => <li key={step} className="flex gap-4 text-sm leading-6 text-slate-700"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-blue-700 text-xs font-black text-white">{index + 1}</span><span>{step}</span></li>)}</ol></div></section>
      <section className="py-10"><h2 className="text-center text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">{config.exampleTitle}</h2><p className="mx-auto mt-3 max-w-2xl text-center text-sm leading-6 text-slate-600">Each example keeps the base value visible so the answer can be checked without relying on a black-box result.</p><div className="mt-8 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[650px] border-collapse text-left text-sm"><thead className="bg-slate-950 text-white"><tr><th className="px-6 py-4 font-bold">Scenario</th><th className="px-6 py-4 font-bold">Substituted formula</th><th className="px-6 py-4 font-bold">Result</th></tr></thead><tbody>{config.examples.map((example) => <tr key={example.scenario} className="border-t border-slate-200"><td className="px-6 py-4 font-semibold text-slate-900">{example.scenario}</td><td className="px-6 py-4 font-mono text-xs text-slate-600">{example.working}</td><td className="px-6 py-4 font-black text-blue-700">{example.result}</td></tr>)}</tbody></table></div></section>
      <section className="py-10"><div className="mb-7 flex items-center justify-center gap-3"><AlertTriangle className="text-amber-600" size={22} /><h2 className="text-2xl font-black tracking-tight text-slate-950">Common {config.title.toLowerCase()} mistakes</h2></div><div className="grid gap-5 md:grid-cols-3">{config.mistakes.map((mistake) => <article key={mistake.title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><CheckCircle2 className="mb-4 text-emerald-600" size={21} /><h3 className="font-black text-slate-950">{mistake.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{mistake.text}</p></article>)}</div></section>
      {config.source && <aside className="my-8 rounded-2xl border border-slate-200 bg-slate-50 p-6 text-sm leading-6 text-slate-600"><strong className="text-slate-900">Method reference:</strong> The formula used here aligns with <a className="ml-1 inline-flex items-center gap-1 font-bold text-blue-700 hover:text-blue-900" href={config.source.href} target="_blank" rel="noreferrer">{config.source.label}<ArrowUpRight size={14} /></a>.</aside>}
      <nav aria-label="Percentage calculator family" className="my-10 rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-300">Percentage calculator cluster</p><h2 className="mt-2 text-2xl font-black">Choose another percentage calculation</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.values(PERCENTAGE_TOOL_CONFIGS).filter(tool => tool.kind !== kind && tool.kind !== 'discount').map(tool => <Link key={tool.kind} href={tool.path} className="rounded-xl border border-white/10 bg-white/[0.06] px-4 py-3 text-sm font-bold text-slate-100 transition hover:border-cyan-300/50 hover:bg-cyan-300/10 hover:text-cyan-200">{tool.title}</Link>)}</div></nav>
      <FAQSchema faqs={config.faqs} /><RelatedTools currentToolId={config.toolId} categoryId="finance" limit={4} />
    </main><Footer />
  </div>;
}
